In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
df = pd.read_csv("D:\Data to deal with\Coffee\index_2.csv")

In [3]:
df = pd.DataFrame(df)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         262 non-null    object
 1   datetime     262 non-null    object
 2   cash_type    262 non-null    object
 3   money        262 non-null    float64
 4   coffee_name  262 non-null    object
dtypes: float64(1), object(4)
memory usage: 10.4+ KB

In [5]:
df.describe()

           money
count  262.00000
mean    26.29771
std      4.25021
min     15.00000
25%     25.00000
50%     27.00000
75%     29.00000
max     33.00000

In [6]:
df.isnull().sum()

date           0
datetime       0
cash_type      0
money          0
coffee_name    0
dtype: int64

In [7]:
df.sample(10)

,date,datetime,cash_type,card,money,coffee_name
2947,2025-02-04,2025-02-04 19:10:27.574,card,ANON-0000-0000-1173,35.76,Cocoa
2516,2024-12-10,2024-12-10 18:21:57.841,card,ANON-0000-0000-0938,35.76,Hot Chocolate
2704,2025-01-03,2025-01-03 16:58:09.420,card,ANON-0000-0000-1070,30.86,Americano with Milk
1941,2024-10-15,2024-10-15 15:54:16.513,card,ANON-0000-0000-0765,25.96,Americano
3307,2025-02-28,2025-02-28 14:47:52.342,card,ANON-0000-0000-1163,25.96,Americano
1394,2024-08-28,2024-08-28 13:48:35.199,card,ANON-0000-0000-0552,27.92,Americano with Milk
2829,2025-01-21,2025-01-21 18:56:15.343,card,ANON-0000-0000-0333,35.76,Latte
1637,2024-09-22,2024-09-22 13:28:14.663,card,ANON-0000-0000-0333,27.92,Americano with Milk
2531,2024-12-13,2024-12-13 12:27:25.453,card,ANON-0000-0000-1004,25.96,Americano
2513,2024-12-09,2024-12-09 13:00:54.913,card,ANON-0000-0000-0802,25.96,Cortado

## Handling Coulms

In [7]:
#Split datetime column into date and time
df[['date','time']] = df['datetime'].str.split(' ',expand = True)

In [8]:
#convert the date column to date so i can extract year , month and day from it
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day_of_week'] = df['date'].dt.day_name()

In [9]:
#convert the date column to datetime so i can extract hour from it
df['datetime'] = pd.to_datetime(df['datetime'])
df['hour'] = df['datetime'].dt.hour

In [10]:
def calss_time(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour <17:
        return 'Afternoon'
    else:
        return 'Evening'

In [11]:
df['time_period'] = df['hour'].apply(calss_time)

In [12]:
#delet datetime coulmn
df.drop(columns='datetime' ,inplace = True)

In [17]:
df['price_tier'] = pd.qcut(df['money'] ,q=3 ,labels=['Low','Medium','High'])

In [23]:
df.to_csv(r"D:\Data Analysis Projects\Project 5 (Coffee)\Python\data.csv", index=False)